### ISSUE TITLE
BUG: tmp file in WINDOWS folder (access denied)

### ISSUE THREAD

**Issue by MJRamon** [XspeedPL/Streamotes#24]
For some reason, mod tries to create tmp file in WINDOWS folder and gets denied access:
Minecraft 1.20.1, Fabric Loader 0.15.11, streamotes-0.9.10+1.20.4

```
[15:42:00] [Render thread/INFO]: [CHAT] <MJRamon> mjrCute
[15:42:00] [Render thread/INFO]: Emote found: mjrCute
[15:42:00] [Render thread/INFO]: Requesting load of mjrCute
[15:42:00] [StreamotesLoader/INFO]: Loading from https://static-cdn.jtvnw.net/emoticons/v2/emotesv2_485996d7a1984b81a5d5b0fd5f1c4c10/default/dark/2.0
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: javax.imageio.IIOException: Can't create cache file!
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.desktop/javax.imageio.ImageIO.createImageInputStream(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.ImageHandler.readImages(ImageHandler.java:42)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.InternalMethods.loadImage(InternalMethods.java:65)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.InternalMethods.loadImage(InternalMethods.java:26)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.addon.TwitchEmotesAPI.loadEmoteImage(TwitchEmotesAPI.java:76)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.addon.pack.TwitchSubscriberPack.loadEmoticonImage(TwitchSubscriberPack.java:66)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at xeed.mc.streamotes.emoticon.AsyncEmoticonLoader.run(AsyncEmoticonLoader.java:37)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: Caused by: java.nio.file.AccessDeniedException: C:\WINDOWS\imageio11250260385932564840.tmp
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.newByteChannel(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.createFile(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.nio.file.TempFileHelper.create(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.nio.file.TempFileHelper.createTempFile(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.createTempFile(Unknown Source)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at com.twelvemonkeys.imageio.stream.FileCache.<init>(FileCache.java:48)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	at com.twelvemonkeys.imageio.stream.BufferedInputStreamImageInputStreamSpi.createInputStreamInstance(BufferedInputStreamImageInputStreamSpi.java:56)
[15:42:00] [StreamotesLoader/INFO]: [STDERR]: 	... 8 more
```

**Comment by XspeedPL** [comment]
Just for the record, no, Streamotes itself does not access system directories or even know about their existence
